name: Build

on:
  workflow_dispatch:
  push:
    branches: [master]

concurrency:
  group: build
  cancel-in-progress: true

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Build with Gradle
        run: cd android && ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: android/app/build/outputs/apk/release/app-release.apk
          if-no-files-found: error
